---
apiVersion: v1
kind: Pod
metadata: 
  name: mynodeportpod
  labels:
    name: myweb
    env: dev
    tier: frontend
spec:
  containers:
    - name: mycontainer
      image: nginx
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80
          name: my-port
      resources:
        requests:   # this is the soft limit
          memory: "64Mi"
          cpu: "250m"
        limits:     # this is the hard limit
          memory: "128Mi"
          cpu: "500m"
    
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport1
spec:
  selector:
    name: myweb
    env: dev
    tier: frontend
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
