---
apiVersion: v1
kind: Pod
metadata: 
  labels:
    name: myweb
    env: dev
    tier: frontend  # Corrected from "froentend" to "frontend"
spec:
  containers:
    - name: mycontainer
      image: nginx
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80
