---
apiVersion: v1
kind: Pod
metadata: 
  name: corrected
  labels:
    name: myweb
    env: dev
    tier: frontend  # Corrected from "froentend" to "frontend"
spec:
  containers:
    - name: mycontainer
      image: nginx
      imagePullPolicy: IfNotPresent
  resources:
    requests:   # this is the soft limit
       memory: "64Mi"
       cpu: "250m"
    limits:     # this is the hard limit
       memory: "128Mi"
       cpu: "500m"
       ports: 
        - containerPort: 80
 