---
apiVersion: v1
kind: Pod
metadata: 
  name: justcheck
  labels:
    app: myapp
    tier: "froentend"
    env: prod
spec:
  containers:
    - name: myapp
      image: nginx
      ports: 
      - containerPort: 80
      resources:
         requests:   # this is the soft limit
            memory: "64Mi"
            cpu: "250m"
         limits:     # this is the hard limit
            memory: "128Mi"
            cpu: "500m"
      env: 
        - name: DEMO_GREETING
          valueFrom:
            configMapKeyRef:
              name: myconfig-demo 
              key: DEMO_GREETING

        - name: DEMO_FAREWELL
          valueFrom:
            configMapKeyRef:
              name: myconfig-demo
              key: DEMO_FAREWELL

        - name: DEMO_CHECK
          valueFrom:
            configMapKeyRef:
              name: myconfig-demo
              key: DEMO_CHECK
